### ISSUE TITLE
Integrate STAC for the ability to transform generator matrices into circuits 

### ISSUE THREAD

**Issue by zuper1998** [Infleqtion/qLDPC#125]
STAC (https://github.com/abdullahkhalids/stac/wiki/guide) already provides some features that are needed for this project. In my opinion, it could be beneficial if it were included as an option.  It can generate stim circuits and also export the circuits int qasm! ^^

**Comment by vtomole** [comment]
Looks like an amazing tool! Thanks for referencing us to it. 

I notice that `stac` is GPL-3.0 licensed which is [incompatible with our Apache 2 licensed project](https://www.apache.org/licenses/GPL-compatibility.html) if the Apache 2 project imports the GPL one. I'm afraid we can't integrate it.

**Comment by perlinm** [comment]
Having said that, `STAC` is of course free to integrate qLDPC into its own pipeline :slightly_smiling_face:

Due to the license incompatibility, though, I'm closing this issue.

**Comment by perlinm** [comment]
It does occur to me though @zuper1998 that we could add, say, example code of how to use `STAC` and `qLDPC` together.  Feel free to open a PR with such an example, which can include (say) instructions for manually installing `STAC`.  We just can't have `qLDPC` use `STAC` internally, or have `STAC` automatically installed by `qLDPC`.
