### ISSUE TITLE
Update `qldpc` to support `ldpc` changes

### ISSUE THREAD

**Issue by dowusu-antwi** [Infleqtion/qLDPC#133]
With the most recent `ldpc==2.1.2`, calls to `get_quasi_cyclic_code_params` in `run_search` fail silently.

```python
import itertools
import run_search
MIN_ORDER = 3
dim_x = 12
for dim_y in range(MIN_ORDER, dim_x + 1):
    dims = (dim_x, dim_y) 
    for exponents in itertools.product(
        range(dim_x), range(dim_y), range(dim_x), range(dim_y)
    ):
        if not redundant_or_trivial(dims, exponents):
            run_search.get_quasi_cyclic_code_params(dims, exponents, min_rate=1/36, num_trials=100, silent=True)
            # returns codes with code_distance=np.nan
```

@singular-value discovered a quick fix: reverting `pip install ldpc==0.1.60`.

`qldpc` should be updated to support the latest [`ldpc`](https://pypi.org/project/ldpc/).

**Comment by perlinm** [comment]
Thanks for filing this issue!  Yes, `v2` of `ldpc` has some breaking changes, and for now we should just pin `ldpc==0.1.60`.  It's definitely a high-priority TODO to update to `ldpc.v2`, but there are a few more changes I would like to make at the same time.
