### ISSUE TITLE
Add `gap.py` to `external/__init__.py`

### ISSUE THREAD

**Issue by vaferrei** [Infleqtion/qLDPC#146]
Thank you for all the awesome work on this library!
Really basic question, but have you considered adding `gap.py` to the external packages `__init__.py`?
Since these helper functions are part of the package either way, it could be useful to allow users to call them directly to use other GAP tools, e.g. QDistRnd, without having to re-implement this functionality themselves or mess around with the project structure.

**Comment by perlinm** [comment]
Ah, this was just an oversight on my part.  Thanks for catching it!

Fixed in #147

**Comment by perlinm** [comment]
@vaferrei done.  I can re-release on PyPI if you need it, otherwise this will go into the next batch of PRs to release.

Even without `gap.py` in `external/__init__.py`, though, I think you should still be able to call `qldpc.external.gap.get_result(*commands)`.  Is that not the case?

**Comment by vaferrei** [comment]
Completely overlooked that, but indeed that is right. Thank you!

**Comment by perlinm** [comment]
Great, thanks for catching this!
